# Generated by Django 4.2 on 2023-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230403_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='featured_product_id',
            field=models.IntegerField(null=True),
        ),
    ]
