# Generated by Django 4.2 on 2023-04-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_collection_featured_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product_id',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='store.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'PENDING'), ('C', 'COMPLETED'), ('F', 'FAILED')], default='P', max_length=1),
        ),
    ]
